<?php

namespace Esprit\RubriqueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentStageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentStageRepository extends EntityRepository
{
        public function getDocumentRub($idRub) {
        return $this->_em->createQuery('
        SELECT
            d
        FROM
            EspritRubriqueBundle:DocumentStage d
        WHERE
            d.rubriqueStage = :rubriqueStage_id
        ORDER BY
            d.id DESC
    ')->setParameter('rubriqueStage_id', $idRub)
            ->getArrayResult();
    }

}
