<?php

namespace Esprit\RubriqueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RubriqueStageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubriqueStageRepository extends EntityRepository
{
}
