<?php

namespace Esprit\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EspEtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspEtudiantRepository extends EntityRepository
{
        public function getEtudiantCourant($id) {
        return $this->_em->createQuery('
        SELECT
            e
        FROM
            EspritUserBundle:EspEtudiant e
        WHERE
            e.id = :etudiant_id
    ')->setParameter('etudiant_id', $id)
            ->getResult();
    }

}
