<?php

namespace Esprit\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    
    public function getNewsDec() {
        return $this->_em->createQuery('SELECT p FROM EspritUserBundle:News p  ORDER BY p.newsDate DESC')
            ->getArrayResult();
    }
    
   


}
