<?php

namespace Esprit\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class EspEtudiantController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Esprit\UserBundle\Controller\EspEtudiantController();
        return $instance;
    }
}
