<?php

namespace Esprit\SeminaireBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SeminaireController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Esprit\SeminaireBundle\Controller\SeminaireController();
        return $instance;
    }
}
