<?php

namespace Esprit\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AbsenceController__JMSInjector
{
    public static function inject($container) {
        require_once 'C:/wamp/www/enligne/app/cache/dev/jms_diextra/proxies/Esprit-UserBundle-Controller-AbsenceController.php';
        $a = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Esprit\\UserBundle\\Controller\\AbsenceController' => array('showAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_79abe7e6aa6a209ef5453c0cc2d6a001f3b1a15c\__CG__\Esprit\UserBundle\Controller\AbsenceController();
        $instance->__CGInterception__setLoader($a);
        return $instance;
    }
}
