<?php

namespace Esprit\SeminaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeminaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeminaireRepository extends EntityRepository
{
    public function getSeminaireLibre ($id)
    {
     
        $stmt = $this->getEntityManager()
                   ->getConnection()
                   ->prepare('SELECT * FROM SEMINAIRE 
                       WHERE ID NOT IN (SELECT ID_SEM FROM INSCRITSEMIN WHERE ID_ET=:id_et)
                      ');
      $stmt->bindValue('id_et', $id);
      $stmt->execute();
      return $stmt->fetchAll();
    }
}
